[package]
name = "rust_cli_blog"
version = "0.0.6"
authors = ["Max Rumsey <max@maxrumsey.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.rusqlite]
version = "0.21.0"
features = ["bundled"]